#!/bin/bash
sudo apt install brightnessctl
sudo apt install ksnip
sudo apt install xfce4-appfinder
sudo apt install i3lock
sudo apt install xfce4-terminal
sudo apt install gnome-system-monitor
sudo apt install thunar
sudo apt install nautilus
sudo apt install gnome-terminal
sudo apt install gnome-settings-daemon
sudo apt install setxkbmap
sudo apt install numlockx
sudo apt install scrot
sudo apt install rofi
sudo apt install pasystray
sudo apt install volumeicon-alsa
sudo apt install lxpolkit
sudo apt install i3lock-fancy
sudo apt install nm-tray
