#!/bin/bash
#
# fluxbox startup-script
#
# Lines starting with a '#' are ignored.

# 设置壁纸（带 1 秒延迟，防止 X 服务器未完全启动）
(sleep 1 && /usr/bin/fbsetbg -a ~/.fluxbox/backgrounds/music-white-black-hd-wallpaper.jpg) &
# (sleep 1 && /usr/bin/fbsetbg -a ~/.fluxbox/backgrounds/zetong-li-TbHYpbi_Gbc-unsplash.jpg) &

# 启动 fcitx5（避免重复运行）
pgrep -x fcitx5 > /dev/null || fcitx5 &
# 启动 fcitx4（避免重复运行）
# pgrep -x fcitx > /dev/null || fcitx &

# 启动网络管理器托盘（避免重复运行）
pgrep -x nm-applet > /dev/null || nm-applet &
# nm-applet &
# nm-tray&

# 启动蓝牙管理器（避免重复运行）
# pgrep -x blueman-applet > /dev/null || blueman-applet &

# 启动conky
# conky&

# 设置普通美式键盘布局
setxkbmap us &
# 设置默认支持英文和中文
# setxkbmap -layout cn,us &
# 设置带有国际字符支持的美国英语键盘布局
# setxkbmap us -variant intl & # 在 us 键盘中添加特殊字符支持 (类似 éóíáú) 

# 使用 numlockx 工具来控制小键盘状态。
# sudo apt install numlockx  # Debian/Ubuntu
numlockx on & # 启用小键盘（默认开启）
# numlockx off &

# 加载 Xmodmap（如果文件存在）
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

# 你希望在 Fluxbox 启动时运行的应用程序  
# 确保 **需要常驻运行的程序** 末尾加上 '&'，否则会阻塞 Fluxbox 启动  
# unclutter -idle 2 &  # 鼠标静止 2 秒后自动隐藏指针  
# wmnd &  # 运行网络监视工具  
# wmsmixer -w &  # 运行音量控制器  
# idesk &  # 在桌面显示图标  

# Debian 相关改动：  
# - `fbautostart` 被加入，并通过简单的检测方法检查其是否存在。  
# - 如果 `fbautostart` 存在，我们会默认启动它。  
# 自动启动其他应用（如果 fbautostart 存在）
# fbautostart 是 Debian 里的一个工具，它的作用是自动运行 ~/.config/autostart/ 目录下的程序，或者其他 XDG 相关的自启动项
command -v fbautostart >/dev/null && fbautostart &
# 最后，我们启动 Fluxbox。因为它是最后运行的应用程序，你必须在它前面加上 exec。
# exec fluxbox
# 如果你想要保存日志:
exec fluxbox -log "~/.fluxbox/log"
