#!/bin/bash
source ~/.zshrc
# 获取当前脚本所在目录
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
LIB_DIR="$SCRIPT_DIR/../lib/Office/"

# 获取右键点击的文件夹或文件路径
selected_item="$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"

# 去除换行符
selected_item=$(echo "$selected_item" | tr -d '\n')

# 调试输出：确认是否获取到了选中的文件夹或文件
echo "选中的项目路径：$selected_item"

# 检查文件/文件夹是否存在
if [ -z "$selected_item" ] || [ ! -e "$selected_item" ]; then
    zenity --error --text="选择的文件或文件夹不存在"
    exit 1
fi

# 执行转换操作（例如复制脚本）
cp "$LIB_DIR/move_subdirfiles_here.sh" "$selected_item"/../move_subdirfiles_here.sh

# 完成后显示信息框
# zenity --info --text="请复制到终端运行：./Office2txt.sh \"$selected_item\""
# gnome-terminal --working-directory="$(pwd)"
gnome-terminal --working-directory="$(pwd)" -- bash -c "./move_subdirfiles_here.sh ; exec zsh"

