#!/bin/bash
# sudo apt-get install nautilus-actions
# 放在 ~/.local/share/nautilus/scripts
# Open_current_directory_by.sh

dapp="thunar"

# 获取用户点击的目录路径
if [ -d "$1" ]; then
  DIR="$1"
else
  DIR="$(dirname "$1")"
fi


# 使用 thunar 打开指定的目录
$dapp "$DIR"

# 使用 Nautilus 打开脚本被执行时的当前目录
# thunar "$(dirname "$0")"
