#!/bin/bash
# docx 转 pdf
# 需要 libreoffice

# 获取当前目录
current_dir=$(pwd)

# 创建 output_pdf 目录（如果不存在的话）
output_dir="$current_dir/output_pdf"
mkdir -p "$output_dir"

# 遍历选中的文件
for file in "$@"; do
    # 检查文件是否为 .doc 或 .docx
    if [[ "$file" == *.doc || "$file" == *.docx ]]; then
        echo "正在转换: $file"
        libreoffice --headless --convert-to pdf "$file" --outdir "$output_dir"
    else
        echo "跳过非 Word 文件: $file"
    fi
done

notify-send "所有文件已转换完成，PDF 保存在 $output_dir 目录中。"

