#!/bin/bash
source ~/.zshrc
# 获取当前脚本所在目录
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
LIB_DIR="$SCRIPT_DIR/../lib/PDF_Tools"

# 获取第一个PDF所在目录作为目标目录
TARGET_DIR="$(dirname "$1")"
TMP_PDF_DIR="$TARGET_DIR/PDF_Tools_WP"

# 如果之前残留了旧目录，先删掉
rm -rf "$TMP_PDF_DIR"

# 复制 PDF_Tools 到目标目录并重命名为 PDF_Tools_WP
cp -r "$LIB_DIR" "$TMP_PDF_DIR"

# 创建 pdfs 子目录
mkdir -p "$TMP_PDF_DIR/pdfs"

# 复制选中的 PDF 文件进去
for pdf in "$@"; do
    cp "$pdf" "$TMP_PDF_DIR/pdfs/"
done

# 切换到 PDF_Tools_WP 执行合并
cd "$TMP_PDF_DIR"

if python3 splitPDFPages.py; then
    # 成功则复制合并结果到目标目录
    cp -r split_pages ../"$TARGET_DIR/PDF拆分结果"
    notify-send "✅ 拆分完成" "已保存：$TARGET_DIR/PDF拆分结果"
else
    # 如果失败
    notify-send "❌ 拆分失败" "请检查"
    exit 1
fi

cd ..

# 删除临时 PDF_Tools_WP 文件夹
rm -rf "$TMP_PDF_DIR"

